graph TD
    stg_locations
    stg_orders
    raw_stores
    raw_items
    order_items
    raw_products
    raw_supplies
    stg_order_items
    raw_orders
    raw_payments
    orders
    stg_customers
    locations
    stg_products
    customers
    supplies
    products
    raw_customers
    stg_supplies
    raw_stores --> stg_locations
    raw_orders --> stg_orders
    stg_orders --> order_items
    stg_products --> order_items
    products --> order_items
    stg_order_items --> order_items
    orders --> order_items
    stg_supplies --> order_items
    supplies --> order_items
    raw_items --> stg_order_items
    stg_orders --> orders
    order_items --> orders
    raw_customers --> stg_customers
    stg_locations --> locations
    raw_products --> stg_products
    stg_orders --> customers
    stg_customers --> customers
    orders --> customers
    stg_supplies --> supplies
    stg_products --> products
    raw_supplies --> stg_supplies
